Repository kir-dev/cmsch, pull requests merged in 2022-01, with the labels that each got.

#36 Add yarn format task in gradle build
  build.gradle.kts
Labels: bug

#37 Rename env vars of client
  src/main/resources/config/application.properties
Labels: bug

#54 Fix eslint and prettier task on gradle build
  build.gradle.kts
  src/main/client/src/components/@commons/ExampleApiCallComponent.tsx
Labels: bug

#86 Purge fontsource fonts, use basic chakra fonts
  src/main/client/package.json
  src/main/client/src/App.tsx
  src/main/client/src/utils/customTheme.ts
  src/main/client/yarn.lock
Labels: enhancement, FRONTEND, priority: very low

#85 Add fun custom banner txt
  src/main/resources/banner.txt
Labels: enhancement, priority: very low

#92 Added Loading component
  src/main/client/src/utils/Loading.tsx
Labels: FRONTEND

#105 Added ServiceContex
  src/main/client/src/App.tsx
  src/main/client/src/components/@commons/Warning.tsx
  src/main/client/src/components/@pages/ErrorPage.tsx
  src/main/client/src/components/@pages/UnauthorizedPage.tsx
  src/main/client/src/utils/AuthContext.tsx
  src/main/client/src/utils/ServiceContext.tsx
  src/main/client/src/utils/toastTitle.ts
  src/main/client/src/utils/useServiceContext.ts
Labels: help wanted, FRONTEND

#60 add basic riddle pages
  src/main/client/src/components/@pages/RiddleCategoryList.tsx
  src/main/client/src/components/@pages/RiddlePage.tsx
  src/main/client/src/utils/configurations.ts
Labels: FRONTEND

#160 Added gtag
  src/main/client/public/index.html
Labels: FRONTEND

#166 Accept attribute fix
  src/main/client/src/components/@pages/AchievementPage.tsx
Labels: bug, FRONTEND

#164 update riddle pages
  src/main/client/src/components/@pages/RiddleCategoryList.tsx
  src/main/client/src/components/@pages/RiddlePage.tsx
Labels: enhancement, FRONTEND, in progress
